# Name: Het Bharatkumar Patel
# SID: 1742431
# CCID: hetbhara
# AnonID: 1000348298
# CMPUT 275, Winter 2023

# Weekly Exercise #5: Matrix Class
# -------------------------------------------


we6_solution: graph_concepts.o digraph.o
	g++ graph_concepts.o digraph.o -o we6_solution

digraph.o: digraph.cpp digraph.h
	g++ -c digraph.cpp

graph_concepts.o: graph_concepts.cpp
	g++ -c graph_concepts.cpp

clean:
	rm *.o we6_solution